name: publish

on:
  push:
    branches:
      - main

jobs:
  publish-to-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@main
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/
      - run: |
          npm ci
          npm run build
      - name: Semantic Release
        run: npx semantic-release --branches main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
